// <auto-generated />
namespace HrSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addeddriver : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addeddriver));
        
        string IMigrationMetadata.Id
        {
            get { return "202001110157398_addeddriver"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
